### ISSUE TITLE
Example Notebook Corr Centrality Community -> ValueError

### ISSUE THREAD

**Issue by nllz** [nllz/bigbang#6]
https://github.com/sbenthall/bigbang/issues/246

**Comment by davidberra** [comment]
the issue seems to be related to the "filter_by_date" function, defined in the notebook, that clears up the whole dataset (then the NaN to integer error comes as an attempt of conversion on an empty value).

@nllz  beware that the date_from_whole and date_to_whole parameters were maybe set outiside of the time frame of your example mailist (humanrights). however, expanding the timeframe of the parameters didnt solve the issue

**Comment by davidberra** [comment]
@sbenthall:
i am not sure why the filter_by_date function takes date_from and date_to as lists and why is reiterated across all the months ...is that because takes monthly snapshots of the overall network?


for i in range(total_month):
    date_from.append(pd.datetime(temp_year,temp_month,1,tzinfo=pytz.utc))
    if temp_month == 12:
        temp_year += 1
        temp_month = 0
    date_to.append(pd.datetime(temp_year,temp_month+1,1,tzinfo=pytz.utc))
    temp_month += 1
...
for k in range(total_month):
    dfs = [filter_by_date(arx.data,
                      date_from[k],
                      date_to[k]) for arx in archives]

**Comment by davidberra** [comment]
ok, the issue has to do with how the parameters "date_from_whole" and "date_to_whole" are set

date_from_whole = [2015,1] #Include June(Start month)
date_to_whole = [2015,12] #Include December(End month)

if the date range set by the parameters is wider than the actual time range of the mail list, some of the dataframes result empty (since the following blocks iterate over all the months) and thus the NaN error

when setting the parameters to a time frame included in the mail list, everything works


it's still not clear to me why what seems should some static filter parameters are then actually then iterables

is it an option to just get rid of time filter?

**Comment by davidberra** [comment]
ok i pushed the following modifications:

-set 'date_from_whole' and 'date_to_whole' as the actual min and max dates in the mailinglist(s)
--> works fine with one single ml; with more, still there are empty data frames, so..

-skip empty data frames when merging them in 'fdf' (filtered data frames)

@sbenthall  does this make sense?

**Comment by sbenthall** [comment]
The short answer is that this notebook was written mostly by an undergraduate who was learning how to use these tools as he went along.

So any modification to this notebook that makes it easier for you to understand and work with is a good thing!

To answer your first question: yes, this notebook looks at monthly snapshots of the activity.

The point of the notebook is to plot the correlation among mailing lists participants between their betweeness centrality and the number of mailing lists (out of several) that they are participating in (during that month, I believe).

I'm not sure which commit you want me to look at specifically. If you copy its link on GitHub into the issue, it will provide a nicely formatted link that will be easy to follow.

**Comment by nllz** [comment]
https://github.com/nllz/bigbang/blob/master/examples/Corr%20between%20centrality%20and%20community%200.1.ipynb
